# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first
Item.create(code: '012-003' , description: 'String Lite 20m 190L 230V d/green cable')
Item.create(code: '012-005' , description: 'Drape Lite  2mx1.5m 456L d/green cable')
Item.create(code: '012-013' , description: 'Ice Lite 5mx0.5m 190L white cable')
Item.create(code: '012-024' , description: 'Magic Garland Lite 180L 2.7m white')
Item.create(code: '012-097' , description: 'Swag Lite 2m 180L white cable')
Item.create(code: '012-098' , description: 'String Lite 20m 190L 230v White')
Item.create(code: '012-104' , description: 'Magic Drape Lite 1mx1.5m 120L white cabl')
Item.create(code: '012-107' , description: 'Magic String Lite 600cm 144L green cable')
Item.create(code: '012-109' , description: 'Giant Ice Lite 4mx1.5m 304L white cable')
Item.create(code: '014-008' , description: 'Quick Fix Extension 10m black cable')
Item.create(code: '014-009' , description: 'Quick Fix Extension 10m white cable')
Item.create(code: '014-010' , description: 'Quick Fix Divider 12 Outlet black cable')
Item.create(code: '014-011' , description: 'Quick Fix Divider 22 Outlet black cable')
Item.create(code: '014-013' , description: 'Quick Fix Extension 3m black cable')
Item.create(code: '014-014' , description: 'Quick Fix Extension 3m white cable')
Item.create(code: '014-017' , description: 'Quick Fix T-Divider black cable')
Item.create(code: '014-032' , description: 'Mains connector for flat cable')
Item.create(code: '014-033' , description: 'Endpiece with hook for flat cable')
Item.create(code: '014-103' , description: 'LED bulb E27 Red')
Item.create(code: '014-233' , description: 'Quick Fix Mains Connector black cable')
Item.create(code: '014-234' , description: 'Quick Fix Mains Connector white cable')
Item.create(code: '014-244' , description: 'AC/DC black')
Item.create(code: '014-246' , description: 'AC/DC white')
Item.create(code: '014-248' , description: 'Quick Fix Divider 12 Outlet white cable')
Item.create(code: '014-249' , description: 'Quick Fix Divider 22 Outlet white cable')
Item.create(code: '014-252' , description: 'Quick Fix Divider Box 5 Outlets 230V')
Item.create(code: '014-253' , description: 'Quick Fix T-Divider white cable')
Item.create(code: '014-309' , description: 'Quick Fix Extension 1m black cable')
Item.create(code: '014-310' , description: 'Quick Fix Extension 1m white cable')
Item.create(code: '014-311' , description: 'Quickfix cable 50cm black')
Item.create(code: '014-418' , description: 'Mains Connector Black with AC/DC')
Item.create(code: '014-419' , description: 'Mains Connector White with AC/DC')
Item.create(code: '014-477' , description: 'Green Garland 2m Warm White LED')
Item.create(code: '014-919' , description: 'Quickfix Divider box 3 LED')
Item.create(code: '014-920' , description: 'Quickfix Divider box 5 LED')
Item.create(code: '014-937' , description: 'Indoor Mains Connector with AC/DC')
Item.create(code: '014-947' , description: '36V Transformer Max 200W/ 5500LED')
Item.create(code: '014-948' , description: 'Transformer to 36V Max 400W/ 11000LED')
Item.create(code: '014-949' , description: '36V Transformer Max 800W/22000LED')
Item.create(code: '015-010' , description: 'QF T-divider 36V transparent')
Item.create(code: '015-011' , description: 'QF 3-Divider 36V transparent')
Item.create(code: '015-012' , description: 'QF extension 1m 36V transparent')
Item.create(code: '015-013' , description: 'QF extension 5m 36V transparent')
Item.create(code: '015-015' , description: '36V Transformer Max 30W/800LED')
Item.create(code: '015-017' , description: 'Gold Crystal chain 4m  no lights')
Item.create(code: '015-024' , description: 'LED E27 Bulbs Warm white')
Item.create(code: '015-076' , description: 'Indoor T-connector transparent')
Item.create(code: '015-083' , description: 'Quick Fix Extension 5m Green 36V')
Item.create(code: '015-084' , description: 'Quick Fix T-Divider Green 36V')
Item.create(code: '015-085' , description: 'Quick Fix Divider 3 Green 36V')
Item.create(code: '015-195' , description: '36V Transformer Max 15W/400LED')
Item.create(code: '015-197' , description: 'QF 3m Extension 36V transparent')
Item.create(code: '015-235' , description: 'Green garlands 2.7mx30cm  360tips')
Item.create(code: '015-593' , description: '36V Transformer Max 60W/1600LED')
Item.create(code: '017-021' , description: 'Crystal clear LED string lite 4m')
Item.create(code: '017-024' , description: 'Gold Crystal string 40 warm white LED 4m')
Item.create(code: '017-041' , description: 'Indoor string lite warm white 12m green')
Item.create(code: '018-015' , description: 'LED Ice Lite 3x0.5m 114 blue LEDs white')
Item.create(code: '018-055' , description: 'String lite 120 pink LED 20m')
Item.create(code: '018-056' , description: 'String lite 120 blue LED 20m')
Item.create(code: '018-079' , description: 'String lite 90 white LED 4.5m black cabl')
Item.create(code: '018-085' , description: 'Giant Ice Lite 304 White LED 4m white ca')
Item.create(code: '018-090' , description: 'Drape Lite 300 White LED 2mx1.5m white')
Item.create(code: '018-091' , description: 'Drape Lite 300 Blue LED  2mx1.5m white')
Item.create(code: '018-274' , description: 'Ice Drop Light 64 White LED')
Item.create(code: '018-281' , description: 'String lite 120 Red LED 20m white cable')
Item.create(code: '018-309' , description: 'String Lite 120 Warm white LED 20m white')
Item.create(code: '018-323' , description: 'String Lite 120 White LED 20m black cbl')
Item.create(code: '018-324' , description: 'String lite 120 White LED 20m white cbl')
Item.create(code: '018-326' , description: 'Flashing String lite White LED 12m white')
Item.create(code: '018-328' , description: 'Flashing String lite Warm white LED 12m')
Item.create(code: '018-342' , description: 'Ice lite 114 Warm white LED 3mx50cm whit')
Item.create(code: '018-348' , description: 'Ice Lite 114 White LED 3x0.5m white cbl')
Item.create(code: '018-349' , description: 'Ice lite 174 White LED 3x0.9m white cbl')
Item.create(code: '018-352' , description: 'Ice lite 114 Warm white LED 3x0.5m white')
Item.create(code: '018-403' , description: 'Flashing String lite 160 White LED 8m wh')
Item.create(code: '018-407' , description: 'Magic String Lite 120 White LED 2.5m bla')
Item.create(code: '023-001' , description: 'Twig Lights (Cavendish)')
Item.create(code: '028-001' , description: 'String lite 120 White LED 36V 12m clear')
Item.create(code: '028-002' , description: 'String lite 120 Warm white LED36V 12m cl')
Item.create(code: '028-019' , description: 'String Lite 120 Warmwhite LED36V 20m grn')
Item.create(code: '028-040' , description: 'Silver Crystal string 40 white LED 4m36V')
Item.create(code: '028-045' , description: 'Ice twig lite (Tyger Valley)')
Item.create(code: '028-048' , description: 'Flash String 120 Warm wht LED 12m36V cl')
Item.create(code: '028-049' , description: 'Flash String lite 120 White LED12m36V cl')
Item.create(code: '028-064' , description: 'Firework 160 LED warm white 1m')
Item.create(code: '032-002' , description: 'Quick Fix Rope motif Pentor 43cm cir')
Item.create(code: '032-004' , description: 'Quick Fix Motif Candle 60x33cm red yello')
Item.create(code: '032-024' , description: 'Quick Fix Motif Snowflake 53cm White')
Item.create(code: '032-025' , description: 'Quick Fix Motif Pentor 43cm white LED')
Item.create(code: '032-026' , description: 'Quick Fix Motif Snowflake blue 53cm LED')
Item.create(code: '112-025' , description: 'Flat rubber 100m cable 200 x E27 sockets')
Item.create(code: '242-015' , description: 'Twisted 90m Incan. Clear Rope Light')
Item.create(code: '244-001' , description: 'Mains Connection set')
Item.create(code: '244-004FH' , description: '4 Way rope lite connector (DL-2W-X-CE)')
Item.create(code: '244-009' , description: 'PET Track for 13mm rope lite')
Item.create(code: '244-034' , description: 'Quick Fix Rope Connector 50cm white')
Item.create(code: '244-217' , description: '10 rope lite splice connectors')
Item.create(code: '248-002' , description: 'LED Rope lite 36/45m Blue')
Item.create(code: '248-057' , description: 'LED Rope lite 45m white')
Item.create(code: '900-003' , description: '2.2m Cone Tree warm white no base')
Item.create(code: '900-007' , description: 'Astero 2D Star Silver (solid outline)')
Item.create(code: '900-013' , description: '4.5m String Cone Tree White LED')
Item.create(code: '900-050' , description: '16m 2Tier Chandelier white LED 2.4&1.55m')
Item.create(code: '922-301' , description: 'Star cone tree 250cm blue LED')
Item.create(code: '923-395' , description: 'Star cone blue 150cm')
Item.create(code: '923-398' , description: 'Star cone tree silver 250cm LED')
Item.create(code: '923-402' , description: 'LED fir tree 2.5m')
Item.create(code: '924-335' , description: 'Meridia Ball 80cm Warm White')
Item.create(code: '924-494' , description: '150cm Meridia Ball White')
Item.create(code: '924-531' , description: '5.5m Tree White LED 36V (RD)')
Item.create(code: '924-647' , description: '5.5m White LED tree')
Item.create(code: '924-732' , description: 'Sky ball LED blue 40cm')
Item.create(code: '931-312' , description: 'Textile star 4.5m gold')
Item.create(code: '931-360' , description: '17cm Organic ball gold')
Item.create(code: '931-361' , description: '17cm Organic ball  red')
Item.create(code: '931-363' , description: '17cm Organic ball white')
Item.create(code: '931-365' , description: '22cm Organic ball gold')
Item.create(code: '931-366' , description: '22cm Organic ball red')
Item.create(code: '931-368' , description: '22cm Organic ball white')
Item.create(code: '931-370' , description: '40cm Ogranic ball gold')
Item.create(code: '931-371' , description: '40cm Organic ball red')
Item.create(code: '931-375' , description: '60cm Organic ball gold')
Item.create(code: '931-376' , description: '60cm Organic ball gold/lights')
Item.create(code: '931-377' , description: '60cm Organic ball red')
Item.create(code: '931-378' , description: '60cm Organic ball red w/lights')
Item.create(code: '931-386' , description: '80cm Organic ball gold w/lights')
Item.create(code: '931-478' , description: 'Stella airball 1.5x1.7x1.5m')
Item.create(code: '931-643' , description: '10cm Organic ball gold')
Item.create(code: '931-843' , description: 'Cone 2.2m warm white')
Item.create(code: '931-866' , description: '12cm Organic ball white')
Item.create(code: '931-881' , description: '10cm Organic ball white')
Item.create(code: '932-871' , description: 'Sparkle Arch')
Item.create(code: '933-344' , description: 'Star ball blue 156cm LED')
Item.create(code: '933-477' , description: 'Meridia Ball 80cm White LED')
Item.create(code: '933-665' , description: 'Sky ball silver 40cm')
Item.create(code: '933-685' , description: 'Wega 85cm LED warm white')
Item.create(code: '933-812' , description: 'Northern Cross motif warm white 100cm')
Item.create(code: '933-827' , description: 'Wega 120cm LED warm white')
Item.create(code: '933-828' , description: 'Orion 95cm LED warm white')
Item.create(code: '938-036' , description: '10cm Organic ball red')
Item.create(code: '938-037' , description: '12cm Organic ball red')
Item.create(code: '938-700' , description: 'Eco Tree 10m 36V White Flash')
Item.create(code: '938-709' , description: 'Pencil Tree white 6.3x3.1x0.37m')
Item.create(code: '939-710' , description: 'Organic gift red w/lights 36V')
Item.create(code: '939-711' , description: 'Organic gift red 60x60x70cm 240V')
Item.create(code: '941-132' , description: 'Magic forest alu cut tree white')
Item.create(code: '941-377' , description: 'Giant Teddy 7.2x6x5.4m warm white')
Item.create(code: '942-517' , description: 'Baobab 4m warm white LED')
Item.create(code: '943-697' , description: 'Organic gift gold warm white 36V')
Item.create(code: '943-987' , description: 'Ball Table Warm White')
Item.create(code: '943-988' , description: 'Ball Chair Warm White')
Item.create(code: '949-049' , description: 'Organic Heart Red')
Item.create(code: 'B06-DRMX' , description: '6cm ball dark red (burgundy) mixed')
Item.create(code: 'B06-TS' , description: '6cm ball turquoise shiny')
Item.create(code: 'B07-BS' , description: '7cm ball blue shiny')
Item.create(code: 'B07-CM' , description: '7cm ball copper matt')
Item.create(code: 'B07-CS' , description: '7cm ball copper shiny')
Item.create(code: 'B07-GM' , description: '7cm ball gold matt')
Item.create(code: 'B07-GRM' , description: '7cm ball green matt')
Item.create(code: 'B07-GRS' , description: '7cm ball green shiny')
Item.create(code: 'B07-GS' , description: '7cm ball gold shiny')
Item.create(code: 'B07-PUS' , description: '7cm Ball purple shiny')
Item.create(code: 'B07-RM' , description: '7cm ball red matt')
Item.create(code: 'B07-RS' , description: '7cm ball red shiny')
Item.create(code: 'B07-SM' , description: '7cm ball silver matt')
Item.create(code: 'B07-SS' , description: '7cm ball silver shiny')
Item.create(code: 'B07-TS' , description: '7cm ball turquoise shiny')
Item.create(code: 'B07-WS' , description: '7cm ball white pearl shiny')
Item.create(code: 'B08-DRMX' , description: '8cm ball dark red (burgundy) mixed')
Item.create(code: 'B08-OMX' , description: '8cm ball salmon orange mixed')
Item.create(code: 'B10-DRS' , description: '10cm ball burgundy (dark red) shiny')
Item.create(code: 'B10-GM' , description: '10cm ball gold matt')
Item.create(code: 'B10-OMX' , description: '10cm ball salmon orange mixed')
Item.create(code: 'B10-RM' , description: '10cm ball red matt')
Item.create(code: 'B10-SM' , description: '10cm ball silver matt')
Item.create(code: 'B10-WS' , description: '10cm ball white pearl shiny')
Item.create(code: 'B15-BM' , description: '15cm ball blue matt')
Item.create(code: 'B15-BS' , description: '15cm ball blue shiny')
Item.create(code: 'B15-CS' , description: '15cm ball copper shiny')
Item.create(code: 'B15-GG' , description: '15cm ball gold glitter')
Item.create(code: 'B15-GM' , description: '15cm ball gold matt')
Item.create(code: 'B15-GRM' , description: '15cm ball green matt')
Item.create(code: 'B15-GRS' , description: '15cm ball green shiny')
Item.create(code: 'B15-GS' , description: '15cm ball gold shiny')
Item.create(code: 'B15-RG' , description: '15cm ball red glitter')
Item.create(code: 'B15-RM' , description: '15cm ball red matt')
Item.create(code: 'B15-RS' , description: '15cm ball red shiny')
Item.create(code: 'B15-SM' , description: '15cm Ball silver matt')
Item.create(code: 'B15-SS' , description: '15cm ball silver shiny')
Item.create(code: 'B15-TG' , description: '15cm ball turquoise glitter')
Item.create(code: 'B15-TS' , description: '15cm ball turquoise shiny')
Item.create(code: 'B15-WS' , description: '15cm ball white pearl shiny')
Item.create(code: 'B20-BM' , description: '20cm ball blue matt')
Item.create(code: 'B20-BS' , description: '20cm ball blue shiny')
Item.create(code: 'B20-GM' , description: '20cm ball gold matt')
Item.create(code: 'B20-GRS' , description: '20cm ball green shiny')
Item.create(code: 'B20-GS' , description: '20cm ball gold shiny')
Item.create(code: 'B20-OS' , description: '20cm ball salmon orange shiny')
Item.create(code: 'B20-RM' , description: '20cm Ball red matt')
Item.create(code: 'B20-RS' , description: '20cm ball red shiny')
Item.create(code: 'B20-SM' , description: '20cm ball silver matt')
Item.create(code: 'B20-SS' , description: '20cm ball silver shiny')
Item.create(code: 'B25-BS' , description: '25cm ball blue shiny')
Item.create(code: 'B25-CS' , description: '25cm ball copper shiny')
Item.create(code: 'B25-GRS' , description: '25cm ball green shiny')
Item.create(code: 'B25-GS' , description: '25cm ball gold shiny')
Item.create(code: 'B25-RS' , description: '25cm ball red shiny')
Item.create(code: 'B25-SS' , description: '25cm ball silver shiny')
Item.create(code: 'B30-GS' , description: '30cm ball gold shiny')
Item.create(code: 'B30-RS' , description: '30cm ball red shiny')
Item.create(code: 'B30-SS' , description: '30cm ball silver shiny')
Item.create(code: 'B40-GS' , description: '40cm ball gold shiny')
Item.create(code: 'B40-RS' , description: '40cm ball red shiny')
Item.create(code: 'B40-SS' , description: '40cm ball silver shiny')
Item.create(code: 'C-0001' , description: '80cm Silver Star Xanita Board')
Item.create(code: 'C-0100' , description: '2.2m Silver Tree Xanita Board')
Item.create(code: 'D-0001' , description: 'Red flowers with bulbs')
Item.create(code: 'D-0002' , description: 'Crystal berries red w/long stems')
Item.create(code: 'D-0003' , description: 'Red berries straight stems')
Item.create(code: 'D-0004' , description: 'Red berries dark curly stems')
Item.create(code: 'D-0005' , description: 'Hanging crystals matt')
Item.create(code: 'D-0006' , description: 'Hanging crystals clear')
Item.create(code: 'D-0007' , description: 'Silver Chunky Tinsel 5m 2009')
Item.create(code: 'D-0010' , description: 'Umcebo Moonlight hummingbird small')
Item.create(code: 'D-0014' , description: 'Wire lizard/chameleon (small)')
Item.create(code: 'D-0015' , description: 'Beaded Bee (large)')
Item.create(code: 'D-0016' , description: 'Beaded lizard/ chameleon (large)')
Item.create(code: 'D-0017' , description: 'Beaded butterfly (large)')
Item.create(code: 'D-0024' , description: 'Vase fibrestone cone w/rattan')
Item.create(code: 'D-0060' , description: 'Bottle Decoration - pink squid')
Item.create(code: 'D-0061' , description: 'Bottle Decoration - blue squid')
Item.create(code: 'D-0062' , description: 'Bottle Decoration - clear squid')
Item.create(code: 'D-0063' , description: 'Bottle Decoration - purple flower')
Item.create(code: 'D-0064' , description: 'Bottle Decoration - blue tri-flower')
Item.create(code: 'D-0065' , description: 'Bottle Decoration - blue starfish')
Item.create(code: 'D-0066' , description: 'Beaded rope - purple 80cm')
Item.create(code: 'D-0067' , description: 'Beaded rope - purple 60cm')
Item.create(code: 'D-0068' , description: 'Beaded rope - purple 40cm')
Item.create(code: 'D-0069' , description: 'Beaded rope - clear 80cm')
Item.create(code: 'D-0070' , description: 'Beaded rope - clear 60cm')
Item.create(code: 'D-0071' , description: 'Beaded rope - clear 40cm')
Item.create(code: 'D-0072' , description: 'Blue perspex pieces (Eco tree)')
Item.create(code: 'F-0001' , description: 'Round Steel Base 2.6x0.6m')
Item.create(code: 'F-0002' , description: 'Round 80cm gold weave base metal')
Item.create(code: 'F-0009' , description: 'Elevated Steel Platform Eco Tree Menlyn')
Item.create(code: 'F-0303' , description: '65cm Chandelier ring for drape lites')
Item.create(code: 'F-0350' , description: 'Frame String cone tree 10m')
Item.create(code: 'F-0400' , description: 'Twig frames for Tyger Valley')
Item.create(code: 'F-0502' , description: '45cm pentor star frame')
Item.create(code: 'F-0506' , description: 'Hanging star gold (solid centre) frame')
Item.create(code: 'F-0509' , description: 'Hanging star silver (solid outline) fram')
Item.create(code: 'F-0510' , description: 'Solid Metal Star 80cm')
Item.create(code: 'F-0520' , description: 'Snowflake Frame')
Item.create(code: 'F-0560' , description: 'Frame Giant Star 1.5m white')
Item.create(code: 'F-0562' , description: 'Frame Giant Star 2m white')
Item.create(code: 'G-0001' , description: 'Green garland 30cm x 2m')
Item.create(code: 'G-0004' , description: '2.8m green lit garland w/baubles R/S/G')
Item.create(code: 'G-0100' , description: 'Green pine tree 145x48cm')
Item.create(code: 'P-1800' , description: 'Projector Monster')
Item.create(code: 'P-GOBO1' , description: 'Gobo Std colour 1 B&W (6s)')
Item.create(code: 'P-GOBO2' , description: 'Gobo Std colour 2 (glass) 6s')
Item.create(code: 'P-M001' , description: 'Colour switch device')
Item.create(code: 'P-M008' , description: 'Sharper')
Item.create(code: 'P-M010' , description: 'Projector - fire effect')
Item.create(code: 'P-M021' , description: 'Projector - falling stars effect')
Item.create(code: 'P-M038' , description: 'Rain protection')
Item.create(code: 'P-M040' , description: 'DMX connector')
Item.create(code: 'P-OBS060' , description: 'Wide Angle Zoom 60mm Shark')
Item.create(code: 'P-OBS300' , description: 'Zoom telelens 300mm Monster')
Item.create(code: 'P-S003' , description: 'Image Rotation')
Item.create(code: 'P-S007' , description: 'Colour Change Device')
Item.create(code: 'P-S008' , description: 'Profile/Sharper')
Item.create(code: 'P-S014' , description: 'Prismatic Lens')
Item.create(code: 'P-S038' , description: 'Rain Protection - Shark projectors')
Item.create(code: 'P-S046' , description: 'Projector stands')
Item.create(code: 'P-S575' , description: 'Shark 575 Projector')
Item.create(code: 'P-Z1' , description: 'Gobo custom (single)')
Item.create(code: 'RA-001' , description: 'Ice Skates')
Item.create(code: 'RA-002' , description: 'Helmets (child/adult)')
Item.create(code: 'RA-003' , description: 'Skating support mascots (seals)')
Item.create(code: 'RA-004' , description: 'Ice scraper')
Item.create(code: 'RA-005' , description: 'Cleaning paddle')
Item.create(code: 'RA-006' , description: 'Spray sprinkler')
Item.create(code: 'RA-007' , description: 'Skate Sharpener')
Item.create(code: 'RC-001' , description: 'Ice mats aluminium')
Item.create(code: 'RC-002' , description: 'Expanded polystyrene 20x10')
Item.create(code: 'RC-003' , description: 'PVC conncection hose')
Item.create(code: 'RC-004' , description: 'Output curves')
Item.create(code: 'RC-005' , description: 'Inlet  Outlet  Return pipes aluminium')
Item.create(code: 'RC-006' , description: 'Glycol pump w/4 PVC hoses')
Item.create(code: 'RC-007' , description: 'Glycol (L)')
Item.create(code: 'RC-008' , description: 'Barrier board 2x1m nylon')
Item.create(code: 'RC-009' , description: 'Barrier door 1x1m nylon')
Item.create(code: 'RC-010' , description: 'Barrier feet (steel)')
Item.create(code: 'RC-011' , description: '50m PVC irrigation hose')
Item.create(code: 'RL-001' , description: 'Reception counters w/ice skate storage')
Item.create(code: 'RL-002' , description: 'Tables 40x40cm')
Item.create(code: 'RL-003' , description: 'Beanbag white')
Item.create(code: 'RL-004' , description: 'Beanbag blue')
Item.create(code: 'RL-005' , description: 'Black plastic chairs')
Item.create(code: 'RL-006' , description: 'Stanchions with feet')
Item.create(code: 'RL-007' , description: 'Acrylic bays for stanchions')
Item.create(code: 'RL-008' , description: 'Fabric arches')
Item.create(code: 'RL-010' , description: 'Ticket Printer')
Item.create(code: 'W-0001' , description: 'Wooden Base - 90x90x90cm')
Item.create(code: 'W-0003' , description: 'Wooden Base - 72x90x90cm')
Item.create(code: 'W-0005' , description: 'Wooden Base - 77x90x90cm')
Item.create(code: 'W-0006' , description: 'Round Wooden Base 2m diam  80cm high')
Item.create(code: 'W-0020' , description: 'Solid wooden star 70cm')
